=== ldtteam/Structurize/src/main/java/com/ldtteam/blockout/blockOut.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="window" type="windowType"/>
    <xs:element name="layout" type="layoutType"/>

    <xs:simpleType name="align">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TOP_LEFT"/>
            <xs:enumeration value="TOP_MIDDLE"/>
            <xs:enumeration value="TOP_RIGHT"/>
            <xs:enumeration value="MIDDLE_LEFT"/>
            <xs:enumeration value="MIDDLE"/>
            <xs:enumeration value="MIDDLE_RIGHT"/>
            <xs:enumeration value="BOTTOM_LEFT"/>
            <xs:enumeration value="BOTTOM_MIDDLE"/>
            <xs:enumeration value="BOTTOM_RIGHT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sizePair">
        <xs:restriction base="xs:string">
            <xs:pattern value="([-+]?\d+)(%|px)?( +([-+]?\d+)(%|px)?)?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fixedSizePair">
        <xs:restriction base="xs:string">
            <xs:pattern value="(-)?\d+( +\d+)?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="windowType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:attribute name="inherit" type="xs:string"/>
        <xs:attribute name="size" type="sizePair"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="height" type="xs:string"/>
        <xs:attribute name="lightbox" type="xs:boolean"/>
        <xs:attribute name="pause" type="xs:boolean"/>
        <xs:attribute name="type" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="VANILLA"/>
                    <xs:enumeration value="FULLSCREEN"/>
                    <xs:enumeration value="FULLSCREEN_VANILLA"/>
                    <xs:enumeration value="FIXED"/>
                    <xs:enumeration value="FIXED_VANILLA"/>
                    <xs:enumeration value="OVERSIZED"/>
                    <xs:enumeration value="OVERSIZED_VANILLA"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="layoutType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xs:complexType>

    <!-- Pane basic attributes -->
    <xs:complexType name="paneType">
        <xs:attribute name="id" type="xs:string"/>

        <xs:attribute name="align" type="align"/>
        <xs:attribute name="size" type="sizePair"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="height" type="xs:string"/>
        <xs:attribute name="pos" type="sizePair"/>
        <xs:attribute name="x" type="xs:string"/>
        <xs:attribute name="y" type="xs:string"/>

        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="enabled" type="xs:boolean"/>
        <xs:attribute name="tooltip" type="xs:string"/>
        <xs:attribute name="onHoverId" type="xs:string"/>

        <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>

    <!-- Abstract text element -->
    <xs:complexType name="textElementType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="textscale" type="xs:string"/>
                <xs:attribute name="textalign" type="align"/>
                <xs:attribute name="color" type="xs:string"/> <!-- overrides all textcolors-->
                <xs:attribute name="textcolor" type="xs:string"/>
                <xs:attribute name="texthovercolor" type="xs:string"/>
                <xs:attribute name="textdisabledcolor" type="xs:string"/>
                <xs:attribute name="shadow" type="xs:boolean"/>
                <xs:attribute name="wrap" type="xs:boolean"/>
                <xs:attribute name="linespace" type="xs:integer"/>
                <xs:attribute name="text" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- View basic attributes and contents -->
    <xs:complexType name="viewType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Master group for all panes that can be used -->
    <xs:group name="paneContainerGroup">
        <xs:choice>
            <xs:element name="layout" type="layoutElementType"/>
            <xs:element name="view" type="viewType"/>
            <xs:element name="zoomdragview" type="zoomDragType"/>
            <xs:element name="group" type="groupType"/>
            <!-- xs:element name="scrollgroup" type="scrollGroupType"/ -->
            <xs:element name="list" type="listType"/>
            <xs:element name="button" type="buttonType"/>
            <xs:element name="buttonimage" type="buttonImageType"/>
            <xs:element name="text" type="textType"/>
            <xs:element name="label" type="labelType"/>
            <xs:element name="input" type="inputType"/>
            <xs:element name="image" type="imageType"/>
            <xs:element name="imagerepeat" type="imageRepeatType"/>
            <xs:element name="gradient" type="gradientType"/>
            <xs:element name="box" type="boxType"/>
            <xs:element name="itemicon" type="itemIconType"/>
            <xs:element name="switch" type="switchType"/>
            <xs:element name="dropdown" type="dropdownType"/>
            <xs:element name="treeview" type="treeViewType"/>
        </xs:choice>
    </xs:group>

    <!-- <layout> -->
    <xs:complexType name="layoutElementType">
        <xs:attribute name="source" use="required"/>
    </xs:complexType>

    <!-- <group> -->
    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="spacing" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <switch> -->
    <xs:complexType name="switchType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="default" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <box> -->
    <xs:complexType name="boxType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="linewidth" type="xs:decimal"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <list> -->
    <xs:complexType name="listType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>
                <xs:attribute name="padding" type="xs:integer"/>
                <xs:attribute name="scrollbarOffset" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <button> -->
    <xs:complexType name="buttonType">
        <xs:complexContent>
            <xs:extension base="textElementType">
                <xs:attribute name="label" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <label> -->
    <xs:complexType name="labelType">
        <xs:complexContent>
            <xs:extension base="textElementType">
                <xs:attribute name="label" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <text> -->
    <xs:complexType name="textType">
        <xs:complexContent>
            <xs:extension base="textElementType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <itemicon> -->
    <xs:complexType name="itemIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="item" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <buttonimage> -->
    <xs:complexType name="buttonImageType">
        <xs:complexContent>
            <xs:extension base="textElementType">
                <!-- Image and Highlight -->
                <xs:attribute name="source" type="xs:string" use="required"/>
                <xs:attribute name="imageoffset" type="fixedSizePair"/>
                <xs:attribute name="imagesize" type="fixedSizePair"/>
                <xs:attribute name="highlight" type="xs:string"/>
                <xs:attribute name="highlightoffset" type="fixedSizePair"/>
                <xs:attribute name="highlightsize" type="fixedSizePair"/>
                <xs:attribute name="disabled" type="xs:string"/>
                <xs:attribute name="disabledoffset" type="fixedSizePair"/>
                <xs:attribute name="disabledsize" type="fixedSizePair"/>
                <!-- Label (optional) -->
                <xs:attribute name="label" type="xs:string"/>
                <xs:attribute name="textoffset" type="fixedSizePair"/>
                <xs:attribute name="textbox" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <image> -->
    <xs:complexType name="imageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="imageoffset" type="fixedSizePair"/>
                <xs:attribute name="imagesize" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="imageRepeatType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="textureoffset" type="fixedSizePair"/>
                <xs:attribute name="texturesize" type="fixedSizePair"/>
                <xs:attribute name="repeatoffset" type="fixedSizePair"/>
                <xs:attribute name="repeatsize" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <gradient> -->
    <xs:complexType name="gradientType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="gradientstart" type="xs:integer"/>
                <xs:attribute name="gradientend" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <input> -->
    <xs:complexType name="inputType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="text" type="xs:string"/>
                <xs:attribute name="maxlength" type="xs:integer"/>
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="colordisabled" type="xs:string"/>
                <xs:attribute name="shadow" type="xs:boolean"/>
                <xs:attribute name="tab" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <dropdown> -->
    <xs:complexType name="dropdownType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>
                <xs:attribute name="padding" type="xs:integer"/>
                <xs:attribute name="maxContentHeight" type="xs:integer"/>
                <xs:attribute name="dropDownSize" type="fixedSizePair"/>
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="textcolor" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <zoom> -->
    <xs:complexType name="zoomDragType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="dragfactor" type="xs:double"/>
                <xs:attribute name="dragenabled" type="xs:boolean"/>
                <xs:attribute name="zoomfactor" type="xs:double"/>
                <xs:attribute name="zoomenabled" type="xs:boolean"/>
                <xs:attribute name="minscale" type="xs:double"/>
                <xs:attribute name="maxscale" type="xs:double"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <tree> -->
    <xs:complexType name="treeViewType">
        <xs:complexContent>
            <xs:extension base="zoomDragType">
                <xs:attribute name="nodeVertDist" type="xs:integer"/>
                <xs:attribute name="nodeToLineHorizDist" type="xs:integer"/>
                <xs:attribute name="lineSize" type="xs:integer"/>
                <xs:attribute name="linePackedColor" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== ldtteam/Structurize/src/main/resources/assets/structurize/gui/windowshapetool.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" size="420 240" pause="false"
        lightbox="false"
        xsi:noNamespaceSchemaLocation="file:../../../../java/com/structurize/blockout/blockOut.xsd">

    <buttonimage label="$(com.structurize.coremod.gui.shapeTool.pickblock)" id="pickMainBlock" pos="49 0" size="86 17"
                 source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>

    <itemicon id="resourceIcon" item="minecraft:gold_block" size="17 17" pos="84 18"/>

    <buttonimage label="$(com.structurize.coremod.gui.shapeTool.ignore)" id="replaceBlocks" pos="49 45" size="86 17"
                 source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>

    <buttonimage label="$(com.structurize.coremod.gui.shapeTool.hollow)" id="hollowShape" pos="49 73" size="86 17"
                 source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>

    <buttonimage id="previousShape" size="14 15" pos="140 0" label="&lt;"
                 source="structurize:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>
    <dropdown id="style" size="129 17" pos="155 0" maxContentHeight="75" dropDownSize="140 75" source="structurize:textures/gui/builderhut/builder_button_medium_large.png" textcolor="black">
        <view size="100% 15">
            <label id="id" size="100% 100%" label="" pos="0 0"/>
            <button id="button" size="100% 100%" label="" pos="0 0"/>
        </view>
    </dropdown>
    <buttonimage id="nextShape" size="14 15" pos="285 0" label="&gt;"
            source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>

    <label label="Width" id="widthLabel" size="20 20" pos="310 0"/>
    <label label="Length" id="lengthLabel" size="20 20" pos="304 25"/>
    <label label="Height" id="heightLabel" size="20 20" pos="306 50"/>

    <input id="width" size="20 20" pos="340 0" maxlength="3"/>
    <input id="length" size="20 20" pos="340 25" maxlength="3"/>
    <input id="height" size="20 20" pos="340 50" maxlength="3"/>

    <view size="120 112" pos="160 80">
        <buttonimage id="rotateLeft" source="structurize:textures/gui/buildtool/rotateleft.png" size="32" pos="0 0"/>
        <buttonimage id="up" source="structurize:textures/gui/buildtool/up.png" size="32" pos="32 0"/>
        <buttonimage id="rotateRight" source="structurize:textures/gui/buildtool/rotateright.png" size="32" pos="64 0"/>
        <buttonimage id="left" source="structurize:textures/gui/buildtool/left.png" size="32" pos="0 32"/>
        <buttonimage id="mirror" source="structurize:textures/gui/buildtool/mirror.png" size="32" pos="32 32"/>
        <buttonimage id="right" source="structurize:textures/gui/buildtool/right.png" size="32" pos="64 32"/>
        <buttonimage id="minus" source="structurize:textures/gui/buildtool/minus.png" size="32" pos="0 64"/>
        <buttonimage id="down" source="structurize:textures/gui/buildtool/down.png" size="32" pos="32 64"/>
        <buttonimage id="plus" source="structurize:textures/gui/buildtool/plus.png" size="32" pos="64 64"/>
        <buttonimage id="confirm" source="structurize:textures/gui/buildtool/confirm.png" size="32" pos="0 96"/>
        <buttonimage id="cancel" source="structurize:textures/gui/buildtool/cancel.png" size="32" pos="64 96"/>
    </view>

    <buttonimage id="undo" source="structurize:textures/gui/buildtool/rotateleft.png" visible="false" size="32 32" pos="350 210" textcolor="Black" texthovercolor="White"/>
</window>

=== ldtteam/Structurize/src/main/resources/assets/structurize/gui/windowscantool.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../java/com/ldtteam/blockout/blockOut.xsd"
        size="420 240" pause="false" lightbox="false">

    <label size="50 11" pos="60 10" color="white" label="$(com.ldtteam.structurize.gui.scanTool.from)"/>
    <input id="pos1x" size="36 18" pos="90 5" maxlength="10"/>
    <input id="pos1y" size="36 18" pos="130 5" maxlength="10"/>
    <input id="pos1z" size="36 18" pos="170 5" maxlength="10"/>

    <label size="50 11" pos="220 10" color="white" label="$(com.ldtteam.structurize.gui.scanTool.to)"/>
    <input id="pos2x" size="36 18" pos="240 5" maxlength="10"/>
    <input id="pos2y" size="36 18" pos="280 5" maxlength="10"/>
    <input id="pos2z" size="36 18" pos="320 5" maxlength="10"/>

    <label size="100 11" pos="72 35" color="white" label="$(com.ldtteam.structurize.gui.scanTool.name)"/>
    <input id="name" size="178 18" pos="130 30" maxlength="40"/>

    <buttonimage id="confirm" source="structurize:textures/gui/buildtool/confirm.png" size="32" pos="145 50"/>
    <buttonimage id="cancel" source="structurize:textures/gui/buildtool/cancel.png" size="32" pos="235 50"/>

    <buttonimage label="$(com.ldtteam.structurize.gui.scanTool.showRes)" id="showRes" pos="140 80" size="129 17"
                 source="structurize:textures/gui/builderhut/builder_button_medium_large.png" textcolor="black"/>
    <input id="filter" size="129 17" pos="140 80" maxlength="25" visible="false"/>

    <list id="resources" size="200 120" pos="10 100">
        <box size="100% 30" linewidth="2">
            <itemicon id="resourceIcon" size="16 16" pos="1 1"/>
            <label id="resourceName" size="144 12" pos="18 1" color="white" wrap="true"/>
            <label id="resourceQuantity" size="30 12" pos="162 1" color="white" textalign="MIDDLE_RIGHT"/>
            <buttonimage label="$(com.ldtteam.structurize.gui.scanTool.remove)" id="removeBlock" pos="20 13" size="86 17"
                         source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
            <buttonimage label="$(com.ldtteam.structurize.gui.scanTool.replace)" id="replaceBlock" pos="105 13" size="86 17"
                         source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
        </box>
    </list>

    <list id="entities" size="200 100" pos="220 100">
        <box size="100% 30" linewidth="2">
            <label id="resourceName" size="100% 12" pos="0 1" color="white" wrap="true"/>
            <buttonimage label="$(com.ldtteam.structurize.gui.scanTool.remove)" id="removeEntity" pos="0 13" size="86 17"
                         source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
        </box>
    </list>

    <buttonimage id="undo" source="structurize:textures/gui/buildtool/rotateleft.png" visible="false" size="32 32" pos="350 208" textcolor="Black" texthovercolor="White"/>
</window>

=== ldtteam/Structurize/src/main/resources/assets/structurize/gui/windowbuildtool.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../java/com/ldtteam/blockout/blockOut.xsd"
        size="420 240" pause="false" lightbox="false">

    <button id="previousBuildingType" size="15 15" pos="0 0" label="&lt;"/>
    <button id="nextBuildingType" size="15 15" pos="125 0" label="&gt;"/>
    <dropdown id="buildingType" size="112 15" pos="14 0" maxContentHeight="75" dropDownSize="140 75">
        <view size="100% 15">
            <label id="id" size="100% 100%" label="" pos="0 0"/>
            <button id="button" size="100% 100%" label="" pos="0 0"/>
        </view>
    </dropdown>

    <button id="previousStyle" size="15 15" pos="140 0" label="&lt;"/>
    <button id="nextStyle" size="15 15" pos="265 0" label="&gt;"/>
    <dropdown id="style" size="112 15" pos="154 0" maxContentHeight="75" dropDownSize="140 75">
        <view size="100% 15">
            <label id="id" size="100% 100%" label="" pos="0 0"/>
            <button id="button" size="100% 100%" label="" pos="0 0"/>
        </view>
    </dropdown>

    <button id="previousSchematic" size="15 15" pos="280 0" label="&lt;"/>
    <button id="nextSchematic" size="15 15" pos="405 0" label="&gt;"/>
    <dropdown id="schematic" size="112 15" pos="294 0" maxContentHeight="75" dropDownSize="140 75">
        <view size="100% 15">
            <label id="id" size="100% 100%" label="" pos="0 0"/>
            <button id="button" size="100% 100%" label="" pos="0 0"/>
        </view>
    </dropdown>

    <button id="rename" size="114 15" pos="293 20" label="Rename" visible="false"/>
    <button id="delete" size="114 15" pos="293 40" label="Delete" visible="false"/>

    <label id="warning" size="70 12" pos="25 45" color="white" label="$(structurize.gui.buildtool.unexpecteddatafixer)" visible="false"/>

    <label size="300 9" pos="60 65" color="white" label="$(com.structurize.gui.buildtool.tip)" textalign="MIDDLE"/>
    <view size="96 128" pos="162 80">
        <button id="rotateLeft" source="structurize:textures/gui/buildtool/rotateleft.png" size="32" pos="0 0"/>
        <button id="up" source="structurize:textures/gui/buildtool/up.png" size="32" pos="32 0"/>
        <button id="rotateRight" source="structurize:textures/gui/buildtool/rotateright.png" size="32" pos="64 0"/>
        <button id="left" source="structurize:textures/gui/buildtool/left.png" size="32" pos="0 32"/>
        <button id="mirror" source="structurize:textures/gui/buildtool/mirror.png" size="32" pos="32 32"/>
        <button id="right" source="structurize:textures/gui/buildtool/right.png" size="32" pos="64 32"/>
        <button id="minus" source="structurize:textures/gui/buildtool/minus.png" size="32" pos="0 64"/>
        <button id="down" source="structurize:textures/gui/buildtool/down.png" size="32" pos="32 64"/>
        <button id="plus" source="structurize:textures/gui/buildtool/plus.png" size="32" pos="64 64"/>
        <button id="confirm" source="structurize:textures/gui/buildtool/confirm.png" size="32" pos="0 96"/>
        <button id="cancel" source="structurize:textures/gui/buildtool/cancel.png" size="32" pos="64 96"/>
    </view>
    <image id="rotation" size="16" pos="258 80"/>
    <box id="wallmode" size="50 100" pos="0 60" color="rgb(255,255,255)" linewidth="1" visible="false">
        <itemicon item="minecraft:cobblestone_wall" size="33 33" pos="10 0"
                  tooltip="$(structurize.gui.buildtool.wallmode)"/>
        <image size="16" pos="17 40" source="structurize:textures/gui/buildtool/wallneg.png"
               tooltip="$(structurize.gui.buildtool.wallneg)"/>
        <buttonimage id="wallreduceneg" size="14 15" pos="2 42" label="-"
                     source="structurize:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>
        <buttonimage id="wallextendneg" size="14 15" pos="33 42" label="+"
                     source="structurize:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>
        <image size="16" pos="17 60" source="structurize:textures/gui/buildtool/wallpos.png"
               tooltip="$(structurize.gui.buildtool.wallpos)"/>
        <buttonimage id="wallreducepos" size="14 15" pos="2 62" label="-"
                     source="structurize:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>
        <buttonimage id="wallextendpos" size="14 15" pos="33 62" label="+"
                     source="structurize:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>
        <image size="16" pos="17 80" source="structurize:textures/gui/buildtool/wallovl.png"
               tooltip="$(structurize.gui.buildtool.wallovl)"/>
        <buttonimage id="wallreduceovl" size="14 15" pos="2 82" label="-"
                     source="structurize:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>
        <buttonimage id="wallextendovl" size="14 15" pos="33 82" label="+"
                     source="structurize:textures/gui/builderhut/builder_button_mini.png" textcolor="black"/>
    </box>

    <button id="pastecomplete"
            tooltip="$(structurize.gui.buildtool.paste)"
            source="structurize:textures/gui/buildtool/copy.png"
            visible="false"
            size="32 32"
            pos="320 210"
            textcolor="Black"
            texthovercolor="White"/>
    <button id="pastenice" tooltip="$(structurize.gui.buildtool.pastenice)" source="structurize:textures/gui/buildtool/paste.png" visible="false" size="32 32" pos="355 210"/>
    <buttonimage id="undoredo"
                 tooltip="$(structurize.gui.undoredo)"
                 source="structurize:textures/gui/buildtool/undoredo.png"
                 visible="true"
                 size="32 32"
                 pos="390 210"
                 textcolor="Black"
                 texthovercolor="White"/>

    <button id="showinvis" tooltip="$(structurize.gui.buildtool.show)" source="structurize:textures/blocks/blocksubstitution.png" size="26 26" pos="25 210"/>
</window>

=== ldtteam/Structurize/src/main/resources/assets/structurize/gui/windowtagtool.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../java/com/ldtteam/blockout/blockOut.xsd"
        pause="false" lightbox="true">
    <label size="100% 9" pos="0 25" textalign="MIDDLE" color="white"
           label="$(com.ldtteam.structurize.gui.tagtool.currenttag)"/>
    <input id="currentTag" size="150 18" pos="135 40" maxlength="30"/>

    <label id="taglistname" size="230 12" pos="135 65" color="white"/>

    <list id="tagposlist" size="230 120" pos="135 80">
        <box size="100% 17" linewidth="2">
            <itemicon id="posblock" size="17 17" pos="0 1"/>
            <text id="tagnames" size="190 25" pos="30 5" textalign="TOP_LEFT" color="white"/>
            <buttonimage id="removeTag" pos="207 1" size="15 15" source="structurize:textures/gui/builderhut/button_x.png" textcolor="black"/>
        </box>
    </list>

    <buttonimage label="$(com.ldtteam.structurize.gui.tagtool.close)" id="closeUI" pos="300 205" size="86 17"
                 source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>

    <buttonimage id="cancel" source="structurize:textures/gui/builderhut/button_x.png" size="13 16" pos="325 5"/>
</window>

=== ldtteam/Structurize/src/main/resources/assets/structurize/gui/windowreplaceblock.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../java/com/ldtteam/blockout/blockOut.xsd"
        pause="false" lightbox="true">
    <label size="100% 11" pos="0 25" textalign="TOP_MIDDLE" color="white"
           label="$(com.ldtteam.structurize.gui.scan.replace.title)"/>
    <input id="name" size="150 18" pos="135 40" maxlength="25"/>

    <itemicon id="resourceIconFrom" size="17 17" pos="0 1"/>
    <label id="resourceNameFrom" size="140 12" pos="30 4" color="white"/>

    <label id="to" label="->" size="140 12" pos="170 4" color="white"/>

    <itemicon id="resourceIconTo" size="17 17" pos="210 1"/>
    <label id="resourceNameTo" size="140 12" pos="240 4" color="white"/>


    <list id="resources" size="250 120" pos="40 65" childspacing="-1">
        <box size="100% 18" linewidth="1">
            <itemicon id="resourceIcon" size="16 16" pos="1 1"/>
            <label id="resourceName" size="135 18" pos="20 0" color="white" wrap="true"/>
            <buttonimage label="$(com.ldtteam.structurize.gui.scantool.select)" id="select" pos="160 1" size="86 17"
                         source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>
        </box>
    </list>

    <buttonimage label="$(com.ldtteam.structurize.gui.placeholder.addtag)" id="addTag" pos="300 35" size="86 17"
                 source="structurize:textures/gui/builderhut/builder_button_medium.png" textcolor="black"/>

    <label id="taglistname" size="30 12" pos="300 50" color="white"/>

    <list id="nbttags" size="130 120" pos="300 65" childspacing="-1">
        <box size="100% 17" linewidth="1">
            <label id="tagname" size="80 12" pos="5 3" color="white"/>
            <buttonimage id="removeTag" pos="105 1" size="15 15" source="structurize:textures/gui/builderhut/button_x.png" textcolor="black"/>
        </box>
    </list>

    <buttonimage id="done" source="structurize:textures/gui/buildtool/confirm.png" size="32" pos="125 185"/>
    <buttonimage id="cancel" source="structurize:textures/gui/buildtool/cancel.png" size="32" pos="215 185"/>
</window>
